#spring:
#  postgres-qa:
#    username: QA
#    password: 1
#    host: localhost
#    port: 5432
#    db-name: qa
#    jdbc-url: jdbc:postgresql://localhost:5432/postgres
#  datasource:
server:
  port: 8081